-- Madplan: table + RLS policies for public read/insert

create table if not exists public.dishes (
  id bigint generated by default as identity primary key,
  navn text not null check (char_length(trim(navn)) > 0)
);

alter table public.dishes enable row level security;

-- Ensure idempotent policy creation

drop policy if exists "dishes_select_public" on public.dishes;
create policy "dishes_select_public"
  on public.dishes
  for select
  to anon, authenticated
  using (true);

drop policy if exists "dishes_insert_public" on public.dishes;
create policy "dishes_insert_public"
  on public.dishes
  for insert
  to anon, authenticated
  with check (char_length(trim(navn)) > 0);

insert into public.dishes (navn)
values ('Lasagne'), ('Kylling i karry'), ('Tacos')
on conflict do nothing;
